function SpawnRegions()
	return {
		{ name = "Muldraugh, KY", file = "media/maps/Muldraugh, KY/spawnpoints.lua" },
		{ name = "Riverside, KY", file = "media/maps/Riverside, KY/spawnpoints.lua" },
		{ name = "Rosewood, KY", file = "media/maps/Rosewood, KY/spawnpoints.lua" },
		{ name = "West Point, KY", file = "media/maps/West Point, KY/spawnpoints.lua" },
		{ name = "Trelai_4x4", file = "media/maps/Trelai_4x4/spawnpoints.lua" },
		{ name = "Trelai_spawns", file = "media/maps/Trelai_spawns/spawnpoints.lua" },
		{ name = "Trelai_storyspawn", file = "media/maps/Trelai_storyspawn/spawnpoints.lua" },
		{ name = "AZSpawn", file = "media/maps/AZSpawn/spawnpoints.lua" },
		{ name = "BedfordFalls", file = "media/maps/BedfordFalls/spawnpoints.lua" },
		{ name = "North", file = "media/maps/North/spawnpoints.lua" },
		{ name = "South", file = "media/maps/South/spawnpoints.lua" },
		{ name = "West", file = "media/maps/West/spawnpoints.lua" },
		{ name = "Blackwood", file = "media/maps/Blackwood/spawnpoints.lua" },
		{ name = "Checkpoint_1", file = "media/maps/Checkpoint_1/spawnpoints.lua" },
		{ name = "Checkpoint_2", file = "media/maps/Checkpoint_2/spawnpoints.lua" },
		{ name = "Checkpoint_3", file = "media/maps/Checkpoint_3/spawnpoints.lua" },
		{ name = "Checkpoint_4", file = "media/maps/Checkpoint_4/spawnpoints.lua" },
		{ name = "Checkpoint_5", file = "media/maps/Checkpoint_5/spawnpoints.lua" },
		{ name = "Checkpoint_6", file = "media/maps/Checkpoint_6/spawnpoints.lua" },
		{ name = "EVAC_Muldraugh", file = "media/maps/EVAC_Muldraugh/spawnpoints.lua" },
		{ name = "FortRedstone", file = "media/maps/FortRedstone/spawnpoints.lua" },
		{ name = "NewEkron", file = "media/maps/NewEkron/spawnpoints.lua" },
		{ name = "Pitstop", file = "media/maps/Pitstop/spawnpoints.lua" },
		{ name = "RavenCreek", file = "media/maps/RavenCreek/spawnpoints.lua" },
		{ name = "researchbase", file = "media/maps/researchbase/spawnpoints.lua" },
		{ name = "The Frigate", file = "media/maps/The Frigate/spawnpoints.lua" },
		{ name = "vehicle_interior", file = "media/maps/vehicle_interior/spawnpoints.lua" },
		{ name = "SpecialfbasvehiclesInteriorsmap", file = "media/maps/SpecialfbasvehiclesInteriorsmap/spawnpoints.lua" },
		{ name = "Elysium_Island", file = "media/maps/Elysium_Island/spawnpoints.lua" },
		{ name = "researchbaseroad", file = "media/maps/researchbaseroad/spawnpoints.lua" },
		{ name = "SaveOurStation_KnoxCountry_World", file = "media/maps/SaveOurStation_KnoxCountry_World/spawnpoints.lua" },
	}
end
